default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  toolbar1: styleselect | bold italic | link image | undo redo
  toolbar2: table | fullscreen | uploadimage | code
  plugins:
    - table
    - fullscreen
    - code
custom:
  <<: *default
